package info.hellena.api.dto;

public record PostDto(String id,
                   String shortId,
                   String publishedAt,
                   String createdAt,
                   String url,
                   String title,
                   String image,
                   Float ratio,
                   String placeholder,
                   Float readTime,
                   SourceDto source,
                   String[] tags,
                   Boolean read,
                   Boolean bookmarked,
                   Boolean upvoted,
                   Boolean commented,
                   BookmarkListDto bookmarkList,
                   String permalink,
                   int numUpvotes,
                   int numComments,
                   String commentsPermalink,
                   CommentDto[] featuredComments,
                   UserDto author,
                   UserDto scout,
                   Integer views,
                   Integer trending,
                   String description,
                   TocItemDto[] toc,
                   String summary,
                   Integer isAuthor,
                   Integer isScout
                   ) {
}
